### ISSUE TITLE
ocm-tunnel should fail with a better error message for non-internal clusters.

### ISSUE THREAD

**Issue by iamkirkbater** [openshift-online/ocm-cli#150]
Currently, if you attempt to use `ocm tunnel` on a cluster that's not private, it will fail with an error message similar to: 

```
channel 0: open failed: administratively prohibited: open failed
stdio forwarding failed
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
client: fatal: failed to establish ssh session (2)
Error: failed to login to cluster: exit status 99
```

A nice-to-have would be to have ocm tunnel check if the cluster is private before attempting to establish a tunnel.

**Comment by igoihman** [comment]
@cblecker FYI

**Comment by cblecker** [comment]
@iamkirkbater I'm not sure what that message is from. This command will work on all clusters, no matter if they are public or private.

**Comment by iamkirkbater** [comment]
Hmm, fair enough. I'll close this issue and if it pops up I'll try to dig a bit deeper into where it was coming from and what could be fixed. 

Thanks!
