### ISSUE TITLE
Can't set default error stream: no such flag -logtostderr

### ISSUE THREAD

**Issue by xueli181114** [openshift-online/ocm-cli#22]
It will cause the error as title due to different go flag package error.
It's better to define flag named logtostderr before set it:
cmd/ocm/main.go line 51
err := flag.Set("logtostderr", "true")

**Comment by jhernand** [comment]
Does this happen with the release binaries? Get it from here: https://github.com/openshift-online/ocm-cli/releases/tag/v0.1.26.

**Comment by xueli181114** [comment]
> Does this happen with the release binaries? Get it from here: https://github.com/openshift-online/ocm-cli/releases/tag/v0.1.26.
No, it doesn't happen to the release binary. It only happened when build locally follow README.

**Comment by jhernand** [comment]
@xueli181114 I am closing this because the preferred method to install is via RPM, Brew or the releases page. Those builds aren't affected by this issue.
