### ISSUE TITLE
CLI/SDK does not submit empty request body.

### ISSUE THREAD

**Issue by tiwillia** [openshift-online/ocm-cli#234]
Specifying no body with POST seems to actually inject something into the request body.

When a request is made such as `echo '' | ocm post /api/accounts_mgmt/v1/access_token` if we inspect the request body, it should satisfy the comparison `requesty.Body == http.NoBody`, but it does not.

Reading the body its a `[]byte{}`, the slice contains a single byte `10`. 

Making the same request with curl results in no response body.

CC @bvulaj

**Comment by jhernand** [comment]
When you do `echo '' | ...` you are generating a request body that contains a new line character:

```
$ echo '' | xxd
00000000: 0a                                       .
```

If you want to send an empty request body then use the `-n` option of the `echo` command:

```
$ echo -n '' | ...
```

Or else use the `--body` option of the `ocm  post` command together with `/dev/null`:

```
$ ocm post ... --body /dev/null
```

Regardless of how you send the body I think it is bad practice to expect `response.Body == http.NoBody` to be true. That pointer comparison will most probably be `false` even if `response.Body` is zero length. It will only be `true` if your server code explicitly replaces zero length responses with `http.NoBody`.

So I don't think this is a bug, If you disagree please elaborate.

**Comment by jhernand** [comment]
I am closing this. If you still think this is a bug please reopen.
