### ISSUE TITLE
ocm-linux-amd64 from the release page for 0.1.57 doesn't seem to work properly

### ISSUE THREAD

**Issue by grdryn** [openshift-online/ocm-cli#319]
I downloaded the binary on a couple of different machines (Fedora 34, RHEL 7), and when I run it it just seems to output several pages of unprintable characters. It's almost as if it's `cat`ing itself to stderr, but that's probably not what's happening.

It also seems that I consistently get a different sha256 for the file than what's listed in the corresponding sha256 file.

@jhernand am I doing something silly?

**Comment by gregsheremeta** [comment]
@mmazur reported the same

**Comment by mmazur** [comment]
The binaries are corrupted.

**Comment by jhernand** [comment]
Looks like the binaries have been partially uploaded. I am checking. Meanwhile I am removing them from the releases page.

**Comment by jhernand** [comment]
This has been fixed in release [0.1.58](https://github.com/openshift-online/ocm-cli/releases/tag/v0.1.58).
