### ISSUE TITLE
`ocm create cluster ...` ReadObject: expect { or , or } or n, but found , error found in #0 byte of ...||..., bigger context ...||...

### ISSUE THREAD

**Issue by jbpratt** [openshift-online/ocm-cli#331]
While exploring creating a cluster using the `create` command, I ran into this parsing error.

```
ocm create cluster test123 \
  --dry-run --ccs --provider=aws \
  --region=us-east-1 \
  --aws-access-key-id=XXXXX \
  --aws-account-id=XXXXX \
  --aws-secret-access-key=XXXX
Error: Failed to create cluster: dry run: unable to create cluster: ReadObject: expect { or , or } or n, but found , error found in #0 byte of ...||..., bigger context ...||...
```

**Comment by jhernand** [comment]
@jbpratt can you run the tool with the `--debug` option ans share the output? Be aware that that output may contain your AWS credentials; make sure to remove them before sharing.

**Comment by jbpratt** [comment]
ocm version: `0.1.59`, installed via the releases page.

:crying_cat_face: running the same command now is now succeeding, I'm not sure why or how to reproduce this.

Going to close this and I can re-open when I hit this again with sufficient details. My apologies.
