### ISSUE TITLE
Not able to hibernate cluster

### ISSUE THREAD

**Issue by rspagnola** [openshift-online/ocm-cli#386]
When running command  ocm hibernate cluster <cluster name> the following error occurs:
Error: status is 400, identifier is '400', code is 'CLUSTERS-MGMT-400' and operation identifier is '$$$$$$$$$$$$$$$$$': The 'hibernate_cluster' capability is not set for org '####################'

How can we enable hibernate capability for the org?

**Comment by zgalor** [comment]
@rspagnola enabling capability requires SREP role permissions and can be via the API:

```
echo '{"key":"capability.organization.hibernate_cluster", "value":"true", "internal":true}' | ocm post /api/accounts_mgmt/v1/organizations/<org_id>/labels
```
