### ISSUE TITLE
`rosa list versions` should support `hosted_control_plane_enabled`

### ISSUE THREAD

**Issue by cben** [openshift-online/ocm-cli#474]
Not all versions allowed for HCP clusters:
```
Failed to create cluster: Version '4.12.0' is not supported by Hosted Control Plane
```
`rosa list versions` is currently not helpful to find which are supported.  
The API does return a `hosted_control_plane_enabled` field.

- [ ] Show a column for this field?
- [ ] Add `--hosted-cp` flag to filter by it?

**Comment by hunterkepley** [comment]
Resolved in https://github.com/openshift/rosa/pull/1144

**Comment by hunterkepley** [comment]
Column is a good idea, but not required by project management
