### ISSUE TITLE
Should not percent-encode given path

### ISSUE THREAD

**Issue by cben** [openshift-online/ocm-cli#6]
cc @tzvatot 

## Use case 1:
```sh
$ ocm --debug get '/api/clusters_mgmt/v1/clusters?size=1'                                                                                                                               2019-09-02T18:27:02+03:00
I0902 18:27:07.176265    1102 connection.go:461] OpenID client secret wasn't provided, will use ''
I0902 18:27:07.176472    1102 token.go:284] Bearer token expires in 7m32.823541563s
I0902 18:27:07.176490    1102 dump.go:49] Request method is GET
I0902 18:27:07.176509    1102 dump.go:50] Request URL is 'https://api.openshift.com/api/clusters_mgmt/v1/clusters%3Fsize=1'
...
  "reason": "The requested resource '/api/clusters_mgmt/v1/clusters?size=1' doesn't exist"
}
```
It's good that `ocm` has a `--parameter` option that adds `?` and `&` and does url encoding.  
But being familiar with curl, I frequently type/paste a URL that already includes query params, and it repeatedly surprises & annoys me that it doesn't work.
Now I finally discovered _why_ it doesn't work: `ocm` encodes the `?`.

## Use case 2:
```bash
$ ocm --debug get /api/clusters_mgmt/v1/clusters/15jo10gj05uh8hncjsdkqf4nc56h4ek6/groups/dedicated-admins/users/a%25b                                                                   2019-09-02T18:24:41+03:00
I0902 18:25:40.498088     748 connection.go:461] OpenID client secret wasn't provided, will use ''
I0902 18:25:40.498309     748 token.go:284] Bearer token expires in 8m59.501706268s
I0902 18:25:40.498329     748 dump.go:49] Request method is GET
I0902 18:25:40.498358     748 dump.go:50] Request URL is 'https://api.openshift.com/api/clusters_mgmt/v1/clusters/15jo10gj05uh8hncjsdkqf4nc56h4ek6/groups/dedicated-admins/users/a%2525b'
...
```

Note that I asked for `a%25b` and actual URL sent had double-encoded `a%2525b`.

This is (1) surprising, I expect `ocm` to act like `curl` where possible and pass URL as-is (2) makes it **impossible** to request URLs like `users/a%2Fb` with encoded slash, without having ocm encode it twice.
(I hope we'll drop the specific goal of accepting slash, percent etc. in IDP user id, but anyway `ocm` should not prevent such requests.)

I propose to disable this encoding and send URL as-is (plus any `--parameter` if given).

## implementation?

I'm not sure, but I suspect encoding happens in the SDK, possibly here:
https://github.com/openshift-online/ocm-sdk-go/blob/bbc57a8e88dff528350e34868f7eb65aeed50ec7/request.go#L107
`URL.Path` field holds the decoded form: https://golang.org/pkg/net/url/#URL
I guess we should either set `.RawPath` field, or better use `URL.Parse()` to set them for us.  (This may also make it easier to combine query params given in `?foo=bar` form with `--parameter` flags.)

No idea what impact such change will have on other SDK uses.

**Comment by jhernand** [comment]
This is addressed by #61. It will be included in the next release.
