### ISSUE TITLE
Don't fail "cluster describe" if the user doesn't have permission to get the details of the account

### ISSUE THREAD

**Issue by jhernand** [openshift-online/ocm-cli#64]
Currently when the "cluster describe" command tries to retrieve the details of the account that owns the cluster in order to print a user friendly "Creator" field. But this fails if the user doesn't have permission to get that account:

```
$ ocm cluster describe 1bj0a09rr22tfkcmuq40eb05v420uhq0 
Error: can't get account '123': Account with ID 123 denied access to perform get on Account with HTTP call GET /api/accounts_mgmt/v1/accounts/123
Usage:
  ocm cluster describe NAME|ID|EXTERNAL_ID [--output] [--short] [flags]
```

This should be changed so that the CLI does the following:

1. If the creator of the cluster is the user running the "cluster describe" command then the account details should be taken from the `/api/accounts_mgmt/v1/current_account` endpoint because the user will always have permission for that.

2. If the creator of the cluster is not the user running the "cluster describe" command then the authorization error should be checked and instead of printing the error message the CLI should print `Creator: N/A` (or similar).

**Comment by jhernand** [comment]
FYI: @kbsingh @tiwillia @bvulaj

**Comment by jhernand** [comment]
The relevant code is here: https://github.com/openshift-online/ocm-cli/blob/e60817491ec5e08e28514faf05b06b925c1439e4/pkg/cluster/describe.go#L56-L80

**Comment by abhgupta** [comment]
@bvulaj , @tiwillia This only works if the user is the creator of the cluster. However, the user should be able to describe clusters that they have access to view. These are clusters that they can see in the cluster list in the OCM console. The API and CLI already provide a way to fetch the cluster owner details (username and name, which is first+last name) on the subscription itself if the --fetchAccounts=true parameter is passed. Does this not suffice to fetch the account details and display in the CLI output for cluster describe?

**Comment by tiwillia** [comment]
It seems a similar error is created during `ocm cluster create`, causing the command to appear to fail when outputting the cluster information. Users do not have permissions to get their own account, rather they have permissions to `GET /current_account` (the same thing `ocm whoami` uses).
